### ISSUE TITLE
Delays are required

### ISSUE THREAD

**Issue by LeonardoDemartino** [aaronsgiles/ymfm#1]
Hi Aaron!
Is there a #define we can use in [ymfm](https://github.com/aaronsgiles/ymfm) to disable the required delays (INSTANT_MODE or something like that)?

If not, how much delay we should add between writes? I suppose it is not a delay in time but in N calls to clock() before some writes(addr, reg). Am I right?

**Comment by aaronsgiles** [comment]
At the moment, there's no such flag. In general, "instant" writes will work fine except for key on/off. Any time you issue a key on or key off, you need to run at least one clock() before sending another one.

Many VGMs were produced from emulators that did not implement the busy flag. This is a problem because the sound programs would poll the busy flag until it was safe to write a command, but since these emulators didn't implement it, they ended up writing the commands as fast as possible, vs. spacing them out like what would happen in real hardware.

For my vgmrender.cpp I take a very conservative approach and only perform one write per 44.1kHz "tick". Essentially this means that each write in the file just queues up the register/data pair, and when we get ready to generate the next sample, we send out the next command in sequence, if there is one pending.

This also applies to using the nuked cores (which need 24 clocks for every 1 on my end). I found that writing the address, clocking 12 times, then writing the data and clocking another 12 seems to work. And then of course only new writes once every 44.1kHz.

**Comment by aaronsgiles** [comment]
As a follow-up to the original issue you [opened in MAME](https://github.com/mamedev/mame/issues/8042), I ran some tests:

I completed my investigation on this and it looks like I was right about it being a timing issue. I modified my vgmrender.cpp to support running nuked in parallel to compare, and also to support output at native sample rate, and this is what I get:
https://aarongiles.com/for/github/ssg_2_ymfm.wav
https://aarongiles.com/for/github/ssg_2_nuked.wav

They are extremely close and I don't see any clicks/noise in ymfm, unless I am missing something. My player is careful to only send one address/data pair per output sample to both cores, which is a crude approximation for how long the busy signal would be high.

**Comment by LeonardoDemartino** [comment]
Yeah, ssg_2 is fine on my end too. The issue is with my example number 4:
https://deflemask.com/ssg_4.vgm
https://deflemask.com/ssg_4_mame.wav
https://deflemask.com/ssg_4_nuked.wav

I added more waits between writes and even the conservative approach of 1:1 with clock/write doesn't seem to fix the issue neither. I still can hear a small noise in between the notes. https://deflemask.com/mame_vs_nuked_4.jpg (up ymfm)
Could you please confirm that ssg_4.vgm in your end with ymfm sounds like ssg_4_nuked.wav?

**Comment by aaronsgiles** [comment]
Oh, I'm sorry, I must have gotten mixed up. I will check out ssg_4 if you're still seeing issues.

**Comment by aaronsgiles** [comment]
Ok, just pushed a fix for this now. There was a possibility of an envelope discontinuity at release time when inverted.

**Comment by LeonardoDemartino** [comment]
I can confirm this fixed the issue on my end. Perfect! I see no more SSG-EG bugs. Many thanks for your time and work! <3
I'm closing this.

**Comment by aaronsgiles** [comment]
Great! Can I ask where these tests come from? Are they artificially created stress tests? Or are they VGMs from a particular game?

**Comment by LeonardoDemartino** [comment]
Those tests are specific parts of songs made by users of DefleMask Tracker. I've updated the tracker to use your new cores and some users noticed all of these differences vs Nuked. After that I isolated the problematic parts of the songs in the tracker and exported them to .vgm for you.
I think we can considerate those little .vgms as SSG-EG stress tests by now.

Btw, you can listen to the full song here:
https://deflemask.com/set_to_0.vgm
