### ISSUE TITLE
c++ version question

### ISSUE THREAD

**Issue by LeonardoDemartino** [aaronsgiles/ymfm#2]
Hello! This is not an actual issue but a simple curiosity question.

Our compilers setup for a tracker project are configured to work with c++14 (on linux, win, macos, ios, android, raspberry pi, steamlink, etc) but this library needs c++17.
We managed to downgrade the minimum required c++ version, from c++17 to c++14, by replacing only std::size and std::clamp. Those two functions are the ONLY ones that relies on c++17.

I was wondering if the use of c++17 is a remanent consequence of the code being initially shared with MAME (which is c++17)? Or there's maybe another reason that I'm missing?

Thanks a lot.

**Comment by aaronsgiles** [comment]
You're right, the dependency on C++17 comes from MAME but is not strong. I just checked in an update that should make everything C++14 compatible.

**Comment by Wohlstand** [comment]
Maybe separately try to make the C++98 version or a pure-C version? Mainly because I have some libraries I do keep being coded in C++98 with a goal to keep the compatibility with the major set of compilers, including the support for several of very ancient of them. Enforcing the C++17 totally breaks this idea at all, and therefore I'll need to try to port the whole thing into C++98 at least (my libraries were coded for C++98 and they can be built on very old compilers just fine).
