### ISSUE TITLE
Pan for OPLL rhythm sound is not properly

### ISSUE THREAD

**Issue by 110-kenichi** [aaronsgiles/ymfm#26]
Pan for OPLL rhythm sound is not properly. Could you please confirm?

ymfm_fm.h: around L300

Before:
> if (RegisterType::OUTPUTS == 1 || m_regs.ch_output_0(choffs))

After:
> if (RegisterType::OUTPUTS >= 1 || m_regs.ch_output_0(choffs))

**Comment by aaronsgiles** [comment]
No, sorry, your proposed change is not correct.

The OPLL chips output the FM on channel 0, and the rhythm on channel 1. This allows external wiring to control the mixing. Just because there are two outputs doesn't mean it's stereo. 😀

In this case it's really two separate mono channels, which you need to mix together if that's the way they are wired up on the system that is using them. (I expect most systems just sum them.)

**Comment by 110-kenichi** [comment]
Ah- I see. Thank you!
