### ISSUE TITLE
SSG-EG issues: the sequel

### ISSUE THREAD

**Issue by LeonardoDemartino** [aaronsgiles/ymfm#3]
Another quirk in the SSG-EG emulation was found!

https://deflemask.com/ssgeg_issue_6_ymfm.wav
https://deflemask.com/ssgeg_issue_6_nuked.wav
https://deflemask.com/ssgeg_issue_6.vgm

**Comment by aaronsgiles** [comment]
Thanks for reporting. Is this with the latest? I ran it using my vgm renderer and the results were closer to nuked than yours. I do hear a bit of an overtone in the nuked that is missing with mine -- is that what you're referring to? Otherwise it's pretty subtle unless I'm missing something:
https://aarongiles.com/for/ymfm/ssg6-ymfm.wav
https://aarongiles.com/for/ymfm/ssg6-nuked.wav

(Outputs are at FM frequency to eliminate resampling side effects.)

**Comment by LeonardoDemartino** [comment]
Hi Aaron! Thanks for those recordings!
I'm referring to something more fundamental. The waveform is being cut when the envelope begins to decrease. Check this images made with your .wavs (up ymfm, down nuked):
https://deflemask.com/ssgeg6_img_1.png
https://deflemask.com/ssgeg6_img_2.png
https://deflemask.com/ssgeg6_img_3.png

It seems that your core is corrupting the phase somehow? This can be heard as little periodic "clicks".

**Comment by aaronsgiles** [comment]
Ok thank you for pointing out the specific problem -- I don't think I would have noticed it without your help! That does seem like an error. I'll look into it.

**Comment by aaronsgiles** [comment]
Ok this should be addressed with the latest commit. Please confirm and close if things look good. Thanks!

**Comment by LeonardoDemartino** [comment]
It seems to be fixed! You rock! <3
